addSbtPlugin("org.scoverage" % "sbt-scoverage" % "2.0.2")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "3.9.13")
addSbtPlugin("com.github.sbt" % "sbt-pgp" % "2.1.2")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "1.2.0")
//addSbtPlugin("com.geirsson" % "sbt-ci-release" % "1.5.3")
//addSbtPlugin("au.com.onegeek" %% "sbt-dotenv" % "2.0.117")
//addSbtPlugin("ch.epfl.scala" % "sbt-scala3-migrate" % "0.3.3")
